Repository ClassCardMLP/ClassCard, pull requests merged in 2023-01, with the labels that each got.

#4 FEAT: 대댓글 비동기까지 완료
  .ebextensions/django.config
  .github/workflows/deploy.yml
  magazine/forms.py
  magazine/migrations/0005_alter_magazine_tag.py
  magazine/migrations/0006_auto_20221229_1453.py
  magazine/migrations/0007_auto_20221229_1455.py
  magazine/models.py
  magazine/templates/magazine/detail.html
  magazine/urls.py
  magazine/views.py
  static/css/magazine_detail.css
Labels: FEAT, FIX

#6 carousel 수정
  magazine/migrations/0008_alter_magazine_tag.py
  magazine/migrations/0009_alter_magazine_tag.py
  templates/main.html
Labels: FIX, DOCS

#7 FEAT: 댓글 부분, 로그인 안 하면 form이 안 보이도록 구현하기
  card/templates/card/detail.html
  card/views.py
  magazine/migrations/0008_alter_magazine_tag.py
  magazine/migrations/0009_alter_magazine_tag.py
  magazine/templates/magazine/detail.html
  static/css/detail.css
  static/css/magazine_detail.css
Labels: FEAT

#8 STYLE:cardcompany 디자인수정
  card/templates/card/cardcompany.html
  card/views.py
  static/css/card.css
Labels: DOCS

#9 Ready
  articles/templates/articles/eventhome.html
  static/css/styles.css
  templates/main.html
Labels: FEAT, FIX, DOCS

#10 fix:main-top3
  config/views.py
  templates/main.html
  templates/tete.html
Labels: FEAT, FIX

#11 DOCS:cardcompany 카드 비율조정
  static/css/card.css
Labels: DOCS

#12 FEAT: 채널톡
  templates/base.html
Labels: FEAT

#13 Ready
  articles/templates/articles/eventhome.html
Labels: FEAT, FIX
